# Whether the resulting build should be minified, or not.
minify: false

# Source and corresponding destination paths for resources. You should
# probably not change these unless you know what you're doing:
src:
  tmp: build/tmp
  css: src/css/style.less
  js:
    - node_modules/sticky-kit/dist/sticky-kit.js
    - node_modules/bootstrap/dist/js/bootstrap.js
    - src/js/*.js
  html: src/**/*.pug
  icons: src/icons/*.svg
  images: src/**/*.{svg,png,jpg,gif,pdf}
  restTmpl: src/rest/template.nunjucks

dist:
  css: dist/css
  js: dist/js
  html: dist
  font: dist/font
  images: dist
  javadoc: dist/java-doc
